/** Dynamic sitemap generated by Next.js — serves at /sitemap.xml */
export default function sitemap() {
  const base = 'https://pxispace.com';
  return [
    { url: base, lastModified: new Date(), changeFrequency: 'weekly', priority: 1.0 },
    { url: `${base}/events`, lastModified: new Date(), changeFrequency: 'daily', priority: 0.9 },
    { url: `${base}/about`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/beta`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5 },
    { url: `${base}/support`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5 },
    { url: `${base}/legal`, lastModified: new Date(), changeFrequency: 'monthly', priority: 0.3 },
    { url: `${base}/child-safety`, lastModified: new Date(), changeFrequency: 'yearly', priority: 0.2 },
    { url: `${base}/privacy_policy`, lastModified: new Date(), changeFrequency: 'yearly', priority: 0.2 },
    { url: `${base}/terms_of_service`, lastModified: new Date(), changeFrequency: 'yearly', priority: 0.2 },
  ];
}
