import { EDITORIAL_STORIES } from '@/content/editorial';
import { allCitySlugs } from '@/lib/seo/cities';

/** Dynamic sitemap generated by Next.js — serves at /sitemap.xml */
export default function sitemap() {
  const base = 'https://pxispace.com';
  const now = new Date();

  const core = [
    { url: base, changeFrequency: 'weekly', priority: 1.0 },
    { url: `${base}/events`, changeFrequency: 'daily', priority: 0.9 },
    { url: `${base}/platform`, changeFrequency: 'weekly', priority: 0.9 },
    { url: `${base}/pricing`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/features/white-label-event-ticketing`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/features/event-promoter-analytics`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/features/shared-event-photo-gallery`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/features/digital-event-passport`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/features/instagram-event-sharing`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/competitors/partiful-luma-alternative`, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/editorial`, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${base}/about`, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/beta`, changeFrequency: 'monthly', priority: 0.5 },
    { url: `${base}/support`, changeFrequency: 'monthly', priority: 0.5 },
    { url: `${base}/faq`, changeFrequency: 'monthly', priority: 0.5 },
    { url: `${base}/legal`, changeFrequency: 'monthly', priority: 0.3 },
    { url: `${base}/child-safety`, changeFrequency: 'yearly', priority: 0.2 },
  ];

  const cities = allCitySlugs().map((slug) => ({
    url: `${base}/discover/${slug}`,
    changeFrequency: 'daily',
    priority: 0.7,
  }));

  const editorial = EDITORIAL_STORIES.map((s) => ({
    url: `${base}/editorial/${s.slug}`,
    changeFrequency: 'monthly',
    priority: 0.5,
    lastModified: s.date ? new Date(s.date) : now,
  }));

  return [...core, ...cities, ...editorial].map((e) => ({ lastModified: now, ...e }));
}
